# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D3WGHyQP34nrlvf7AYTKqhv_1-5czeiN
"""

!pip install timm

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import timm
from tqdm import tqdm
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

dataset_path = "/content/drive/MyDrive/real_and_fake_face"

IMG_SIZE = 224
BATCH_SIZE = 32

train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize([0.5,0.5,0.5], [0.5,0.5,0.5])
])

val_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize([0.5,0.5,0.5], [0.5,0.5,0.5])
])

import os
print(os.listdir('/content/drive/MyDrive'))

!unzip "/content/drive/MyDrive/real_and_fake_face.zip" -d "/content/dataset"

dataset_path = "/content/drive/MyDrive/archive (4)"

import os
print(os.listdir(dataset_path))

print(os.listdir(dataset_path + "/real_and_fake_face"))

import shutil
import os
base_dir = "/content/faces_dataset"
real_dir = os.path.join(base_dir, "real")
fake_dir = os.path.join(base_dir, "fake")
os.makedirs(real_dir, exist_ok=True)
os.makedirs(fake_dir, exist_ok=True)
source_real = dataset_path + "/real_and_fake_face/training_real"
source_fake = dataset_path + "/real_and_fake_face/training_fake"
for file in os.listdir(source_real):
    shutil.copy(os.path.join(source_real, file), real_dir)
for file in os.listdir(source_fake):
    shutil.copy(os.path.join(source_fake, file), fake_dir)
print("Dataset organized successfully")

from torch.utils.data import random_split
full_dataset = datasets.ImageFolder(base_dir, transform=train_transform)
print(full_dataset.classes)
print("Total Images:", len(full_dataset))

train_size = int(0.7 * len(full_dataset))
val_size = int(0.15 * len(full_dataset))
test_size = len(full_dataset) - train_size - val_size
train_dataset, val_dataset, test_dataset = random_split(
    full_dataset,
    [train_size, val_size, test_size]
)
train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)
val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)
test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)
print("Train Size:", len(train_dataset))
print("Validation Size:", len(val_dataset))
print("Test Size:", len(test_dataset))

class ChannelAttention(nn.Module):

    def __init__(self, in_planes, ratio=8):
        super(ChannelAttention, self).__init__()

        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)

        self.fc = nn.Sequential(
            nn.Conv2d(in_planes, in_planes // ratio, 1, bias=False),
            nn.ReLU(),
            nn.Conv2d(in_planes // ratio, in_planes, 1, bias=False)
        )

        self.sigmoid = nn.Sigmoid()

    def forward(self, x):

        avg_out = self.fc(self.avg_pool(x))
        max_out = self.fc(self.max_pool(x))

        out = avg_out + max_out

        return self.sigmoid(out)


class SpatialAttention(nn.Module):

    def __init__(self, kernel_size=7):
        super(SpatialAttention, self).__init__()

        self.conv = nn.Conv2d(
            2,
            1,
            kernel_size,
            padding=kernel_size//2,
            bias=False
        )

        self.sigmoid = nn.Sigmoid()

    def forward(self, x):

        avg_out = torch.mean(x, dim=1, keepdim=True)

        max_out, _ = torch.max(x, dim=1, keepdim=True)

        x = torch.cat([avg_out, max_out], dim=1)

        x = self.conv(x)

        return self.sigmoid(x)


class CBAM(nn.Module):

    def __init__(self, channels):
        super(CBAM, self).__init__()

        self.ca = ChannelAttention(channels)
        self.sa = SpatialAttention()

    def forward(self, x):

        x = x * self.ca(x)

        x = x * self.sa(x)

        return x

class DeepFakeDetector(nn.Module):

    def __init__(self):
        super(DeepFakeDetector, self).__init__()

        self.backbone = timm.create_model(
            'efficientnet_b0',
            pretrained=True,
            num_classes=0
        )

        self.cbam = CBAM(1280)

        self.classifier = nn.Sequential(

            nn.Linear(1280, 512),

            nn.ReLU(),

            nn.Dropout(0.3),

            nn.Linear(512, 2)
        )

    def forward(self, x):

        x = self.backbone.forward_features(x)

        x = self.cbam(x)

        x = nn.functional.adaptive_avg_pool2d(x, 1)

        x = x.view(x.size(0), -1)

        x = self.classifier(x)

        return x

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = DeepFakeDetector().to(device)

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=0.0001
)

print(device)

EPOCHS = 5

train_losses = []
val_losses = []

for epoch in range(EPOCHS):

    model.train()

    running_loss = 0

    for images, labels in tqdm(train_loader):

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    train_loss = running_loss / len(train_loader)

    train_losses.append(train_loss)

    model.eval()

    running_val_loss = 0

    with torch.no_grad():

        for images, labels in val_loader:

            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)

            loss = criterion(outputs, labels)

            running_val_loss += loss.item()

    val_loss = running_val_loss / len(val_loader)

    val_losses.append(val_loss)

    print(f'Epoch {epoch+1}/{EPOCHS}')

    print(f'Train Loss: {train_loss:.4f}')

    print(f'Validation Loss: {val_loss:.4f}')

model.eval()

y_true = []
y_pred = []

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, preds = torch.max(outputs, 1)

        y_true.extend(labels.cpu().numpy())
        y_pred.extend(preds.cpu().numpy())

print(classification_report(y_true, y_pred))

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(6,6))

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

plt.xlabel('Predicted')

plt.ylabel('Actual')

plt.title('Confusion Matrix')

plt.show()

torch.save(model.state_dict(), "deepfake_detector.pth")

print("Model Saved Successfully")

from google.colab import files

files.download("deepfake_detector.pth")

from PIL import Image

classes = ['fake', 'real']

def predict_image(image_path):

    image = Image.open(image_path).convert('RGB')

    image = val_transform(image)

    image = image.unsqueeze(0).to(device)

    model.eval()

    with torch.no_grad():

        output = model(image)

        _, pred = torch.max(output, 1)

    print("Prediction:", classes[pred.item()])

def predict_and_show(image_path):

    image = Image.open(image_path).convert('RGB')

    plt.imshow(image)
    plt.axis('off')

    transformed = val_transform(image)

    transformed = transformed.unsqueeze(0).to(device)

    model.eval()

    with torch.no_grad():

        output = model(transformed)

        _, pred = torch.max(output, 1)

    plt.title(f'Prediction: {classes[pred.item()]}')

    plt.show()

predict_and_show('/content/test.jpg')
predict_image('/content/test.jpg')

plt.figure(figsize=(10,5))

plt.plot(train_losses, label='Train Loss')

plt.plot(val_losses, label='Validation Loss')

plt.xlabel('Epoch')

plt.ylabel('Loss')

plt.title('Training vs Validation Loss')

plt.legend()

plt.show()

!pip install grad-cam

import cv2
import numpy as np

from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image

target_layer = model.backbone.conv_head

cam = GradCAM(
    model=model,
    target_layers=[target_layer]
)

from PIL import Image

def visualize_gradcam(image_path):

    image = Image.open(image_path).convert('RGB')

    image_resized = image.resize((224,224))

    rgb_img = np.array(image_resized).astype(np.float32) / 255.0

    input_tensor = val_transform(image_resized).unsqueeze(0).to(device)

    grayscale_cam = cam(
        input_tensor=input_tensor
    )[0]

    visualization = show_cam_on_image(
        rgb_img,
        grayscale_cam,
        use_rgb=True
    )

    plt.figure(figsize=(10,5))

    plt.subplot(1,2,1)
    plt.imshow(rgb_img)
    plt.title("Original Image")
    plt.axis('off')

    plt.subplot(1,2,2)
    plt.imshow(visualization)
    plt.title("Grad-CAM")
    plt.axis('off')

    plt.show()

visualize_gradcam('/content/test.jpg')
print('RED/YELLOW REGION - HIGH ACTIVATION')
print('BLUE/GREEN REGION - LOW ACTIVATION')

!jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace *.ipynb